# deploy_wazuh_agent.yml
---
- name: Instalar e configurar o agente Wazuh em Linux
  hosts: all
  become: yes

  tasks:
    # Etapa 1: Verificar se o agente já está instalado para garantir a idempotência
    - name: Get installed services facts
      ansible.builtin.service_facts:

    - name: Check if Wazuh Agent service already exists
      ansible.builtin.set_fact:
        service_exists: "{{ 'wazuh-agent.service' in ansible_facts.services }}"

    # Etapa 2: Download do pacote de instalação
    # A variável 'wazuh_agent_deb_url' deve ser fornecida pelo AWX
    - name: Download the Wazuh agent .deb package
      ansible.builtin.get_url:
        url: "{{ wazuh_agent_deb_url }}"
        dest: "/tmp/wazuh-agent.deb"
        mode: '0644'
      when: not service_exists

    # Etapa 3: Instalação do agente usando o pacote .deb baixado
    # As variáveis de ambiente são injetadas para configurar o agente durante a instalação
    - name: Install Wazuh agent from .deb package
      ansible.builtin.apt:
        deb: "/tmp/wazuh-agent.deb"
      environment:
        WAZUH_MANAGER: "{{ wazuh_manager }}"
        WAZUH_AGENT_GROUP: "{{ wazuh_agent_group | default('default') }}" # Usa 'default' se a variável não for passada
        WAZUH_REGISTRATION_PASSWORD: "{{ wazuh_registration_password }}"
      when: not service_exists
      notify: # Dispara o handler para gerenciar o serviço somente se a instalação ocorrer
        - Manage Wazuh Service

    # Etapa 4: Limpeza do arquivo de instalação
    - name: Clean up the downloaded .deb package
      ansible.builtin.file:
        path: "/tmp/wazuh-agent.deb"
        state: absent
      when: not service_exists

  # Handlers são executados apenas se "notificados" por uma tarefa que fez uma mudança.
  # Isso evita reiniciar o serviço desnecessariamente.
  handlers:
    - name: Manage Wazuh Service
      listen: "Manage Wazuh Service"
      block:
        - name: Reload systemd manager configuration
          ansible.builtin.systemd:
            daemon_reload: yes

        - name: Enable and start Wazuh agent service
          ansible.builtin.systemd:
            name: wazuh-agent
            enabled: yes
            state: started