---
- name: Instalar K3s nas VMs
  hosts: all
  become: yes
  tasks:  
    - name: Instalar dependências básicas
      package:
        name:
          - curl
          - wget
          - ca-certificates
        state: present
    
    - name: Baixar script de instalação do K3s
      get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s-install.sh
        mode: '0755'
    
    - name: Instalar K3s
      shell: |
        INSTALL_K3S_EXEC="--write-kubeconfig-mode 644" /tmp/k3s-install.sh
      args:
        creates: /usr/local/bin/k3s
    
    - name: Aguardar K3s inicializar
      wait_for:
        port: 6443
        host: localhost
        delay: 10
        timeout: 300
    
    - name: Verificar status do K3s
      systemd:
        name: k3s
        state: started
        enabled: yes
    
    - name: Obter versão do K3s instalada
      command: k3s --version
      register: k3s_version
      changed_when: false
    
    - name: Mostrar versão instalada
      debug:
        msg: "K3s instalado com sucesso: {{ k3s_version.stdout_lines[0] }}"
    
    - name: Verificar status dos nodes
      shell: k3s kubectl get nodes
      register: k3s_nodes
      changed_when: false
    
    - name: Mostrar nodes do cluster
      debug:
        msg: "{{ k3s_nodes.stdout_lines }}"
