---
- name: Run OpenSCAP for Master Node
  hosts: master
  vars:
    scap_version: "0.1.73"
    scap_benchmark: >-
      {% if ansible_distribution_version == '24.04' %}ssg-ubuntu2404-ds.xml
      {% elif ansible_distribution_version == '22.04' %}ssg-ubuntu2204-ds.xml
      {% else %}ssg-ubuntu2004-ds.xml{% endif %}
    scap_profile: "xccdf_org.ssgproject.content_profile_cis_server_l1"

  tasks:
    - name: Add universe repository
      ansible.builtin.apt_repository:
        repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe"
        state: present
      when: ansible_distribution_release in ['jammy', 'noble']

    - name: Update and upgrade packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - libopenscap8
          - ssg-debderived
          - unzip
        state: present

    - name: Ensure SCAP content directory exists
      ansible.builtin.file:
        path: /usr/share/xml/scap/ssg/content/
        state: directory
        mode: '0755'

    - name: Check if SCAP content is already installed
      ansible.builtin.stat:
        path: /usr/share/xml/scap/ssg/content/.scap_installed
      register: scap_installed

    - name: Download SCAP Security Guide
      ansible.builtin.get_url:
        url: "https://github.com/ComplianceAsCode/content/releases/download/v{{ scap_version }}/scap-security-guide-{{ scap_version }}.zip"
        dest: "/tmp/scap-security-guide-{{ scap_version }}.zip"
      when: not scap_installed.stat.exists

    - name: Unzip SCAP content
      ansible.builtin.unarchive:
        src: "/tmp/scap-security-guide-{{ scap_version }}.zip"
        dest: /usr/share/xml/scap/ssg/content/
        remote_src: yes
      when: not scap_installed.stat.exists

    - name: Mark SCAP as installed
      ansible.builtin.file:
        path: /usr/share/xml/scap/ssg/content/.scap_installed
        state: touch
      when: not scap_installed.stat.exists

    - name: Run CIS scan
      ansible.builtin.command: >-
        oscap xccdf eval
        --profile {{ scap_profile }}
        --report /tmp/{{ ansible_hostname }}-cis-report.html
        /usr/share/xml/scap/ssg/content/scap-security-guide-{{ scap_version }}/{{ scap_benchmark }}
      register: scan_result
      ignore_errors: yes

    - name: Collect scan report
      ansible.builtin.slurp:
        src: /tmp/{{ ansible_hostname }}-cis-report.html
      register: slurped_report

    - name: Setup reports directory on master
      ansible.builtin.file:
        path: /home/master/reports
        state: directory
        mode: '0755'
      delegate_to: master
      run_once: true

    - name: Save master report
      ansible.builtin.copy:
        content: "{{ slurped_report.content | b64decode }}"
        dest: "/home/master/reports/master-{{ ansible_date_time.date }}-report.html"
        mode: '0644'
      delegate_to: master